/* SET GLOBAL local_infile=1; */

CREATE /*TEMPORARY*/ TABLE file1 (
  INVENTO VARCHAR(255),
  INVENTOR VARCHAR(255),
  PROFESIONAL_ASIGANDO_AL_INVENTO VARCHAR(255),
  EL_PROFESIONAL_ES_JEFE_DEL_AREA VARCHAR(255),
  FECHA_CONTRATO_PROFESIONAL VARCHAR(255),
  SALARIO INT,
  COMISION INT,
  AREA_INVEST_DEL_PROF VARCHAR(255),
  RANKING SMALLINT,
  ANIO_DEL_INVENTO SMALLINT,
  PAIS_DEL_INVENTO VARCHAR(255),
  PAIS_DEL_INVENTOR VARCHAR(255),
  REGION_DEL_PAIS VARCHAR(255),
  CAPITAL VARCHAR(255),
  POBLACION_DEL_PAIS BIGINT,
  AREA_EN_KM2 INT,
  FRONTERA_CON VARCHAR(255),
  NORTE CHAR(1),
  SUR CHAR(1),
  ESTE CHAR(1),
  OESTE CHAR(1)
);
TRUNCATE TABLE file1;

LOAD DATA LOCAL INFILE 'C:/proyectos/USAC/Bases1/Patent-Office/patentOffice-API/database/CargaP-I.csv'
    INTO TABLE file1
    CHARACTER SET latin1
    FIELDS TERMINATED BY ';'
    LINES TERMINATED BY '\r\n'
    IGNORE 1 LINES
    (INVENTO, INVENTOR, PROFESIONAL_ASIGANDO_AL_INVENTO, EL_PROFESIONAL_ES_JEFE_DEL_AREA, 
        FECHA_CONTRATO_PROFESIONAL, SALARIO, COMISION, AREA_INVEST_DEL_PROF, RANKING, 
        ANIO_DEL_INVENTO, PAIS_DEL_INVENTO, PAIS_DEL_INVENTOR, REGION_DEL_PAIS, CAPITAL, 
        POBLACION_DEL_PAIS, AREA_EN_KM2, FRONTERA_CON, NORTE, SUR, ESTE, OESTE);


CREATE TEMPORARY TABLE file2 (
    NOMBRE_ENCUESTA VARCHAR(255),
    PREGUNTA VARCHAR(255),
    RESPUESTAS_POSIBLES VARCHAR(255),
    RESPUESTA_CORRECTA VARCHAR(255),
    PAIS VARCHAR(255),
    RESPUESTA_PAIS CHAR(1)
);
TRUNCATE TABLE file2;

LOAD DATA LOCAL INFILE 'C:/proyectos/USAC/Bases1/Patent-Office/patentOffice-API/database/CargaP-II.csv'
    INTO TABLE file2
    CHARACTER SET latin1
    FIELDS TERMINATED BY ';'
    LINES TERMINATED BY '\r\n'
    IGNORE 1 LINES
    (NOMBRE_ENCUESTA, PREGUNTA, RESPUESTAS_POSIBLES, RESPUESTA_CORRECTA, 
        PAIS, RESPUESTA_PAIS);

CREATE TEMPORARY TABLE file3 (
    NOMBRE_REGION VARCHAR(255),
    REGION_PADRE VARCHAR(255)
);
TRUNCATE TABLE file3;

LOAD DATA LOCAL INFILE 'C:/proyectos/USAC/Bases1/Patent-Office/patentOffice-API/database/CargaP-III.csv'
    INTO TABLE file3
    CHARACTER SET latin1
    FIELDS TERMINATED BY ';'
    LINES TERMINATED BY '\r\n'
    IGNORE 1 LINES
    (NOMBRE_REGION, REGION_PADRE);

/*
DROP TEMPORARY TABLE file1;
DROP TEMPORARY TABLE file2;
DROP TEMPORARY TABLE file3;
*/